import Head from 'next/head'
import { useRouter } from 'next/router'
import { Box, Button, Flex } from '@radix-ui/themes'

import styles from '@/styles/Home.module.scss'


export default function Home() {
  const router = useRouter()

  const handlePushups = () => {
    router.push( '/pushups' )
  }

  const handleSitups = () => {

  }

  return (
    <>
      <Head>
        <title>Pushup counter</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={ `${ styles.main }` }>
        <Flex gap='3'>
          <Box>
            <Button variant='classic' color='orange' onClick={ handlePushups }>
              Pushups
            </Button>
          </Box>

          <Box>
            <Button variant='classic' color='crimson' onClick={ handleSitups }>
              Situps
            </Button>
          </Box>
        </Flex>
      </main>
    </>
  )
}
