import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { Box, Button, Flex } from '@radix-ui/themes'


export default function Home() {
  const handlePushups = () => {

  }

  const handleSitups = () => {

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={ `${ styles.main }` }>
        <Flex gap='3'>
          <Box>
            <Button variant='classic' color='orange' onClick={ handlePushups }>
              Pushups
            </Button>
          </Box>

          <Box>
            <Button variant='classic' color='crimson' onClick={ handleSitups }>
              Situps
            </Button>
          </Box>
        </Flex>
      </main>
    </>
  )
}
